Dealer.where(dealer_focus_id: "DFC0035", dealer_name: 'Test Dealer 1').first_or_create
Dealer.where(dealer_focus_id: "DFC0025", dealer_name: 'Test Dealer 2').first_or_create
Dealer.where(dealer_focus_id: "DFC0032", dealer_name: 'Test Dealer 3').first_or_create
Dealer.where(dealer_focus_id: "DFC0036", dealer_name: 'Test Dealer 4').first_or_create
Dealer.where(dealer_focus_id: "DFC0033", dealer_name: 'Test Dealer 5').first_or_create
Dealer.where(dealer_focus_id: "DFC0037", dealer_name: 'Test Dealer 6').first_or_create
Dealer.where(dealer_focus_id: "DFC0030", dealer_name: 'Test Dealer 7').first_or_create
Dealer.where(dealer_focus_id: "DFC0022", dealer_name: 'Test Dealer 8').first_or_create
Dealer.where(dealer_focus_id: "DFC0034", dealer_name: 'Test Dealer 9').first_or_create
Dealer.where(dealer_focus_id: "DFC0027", dealer_name: 'Test Dealer 10').first_or_create
Dealer.where(dealer_focus_id: "DFC0031", dealer_name: 'Test Dealer 11').first_or_create
Dealer.where(dealer_focus_id: "DFC0028", dealer_name: 'Test Dealer 12').first_or_create
Dealer.where(dealer_focus_id: "DFC0038", dealer_name: 'Test Dealer 13').first_or_create
Dealer.where(dealer_focus_id: "DFC0040", dealer_name: 'Test Dealer 14').first_or_create
Dealer.where(dealer_focus_id: "DFC0007", dealer_name: 'Test Dealer 15').first_or_create
Dealer.where(dealer_focus_id: "DFC0016", dealer_name: 'Test Dealer 16').first_or_create
Dealer.where(dealer_focus_id: "DFC0042", dealer_name: 'Test Dealer 17').first_or_create
Dealer.where(dealer_focus_id: "DFC0029", dealer_name: 'Test Dealer 18').first_or_create
Dealer.where(dealer_focus_id: "DFC0041", dealer_name: 'Test Dealer 19').first_or_create
Dealer.where(dealer_focus_id: "DFC0023", dealer_name: 'Test Dealer 20').first_or_create